import type { Metadata } from 'next';
import { Geist, Geist_Mono, Roboto_Condensed } from 'next/font/google';
import './globals.css';
import QueryProvider from '@/lib/QueryProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const robotoCondensed = Roboto_Condensed({
  variable: '--font-roboto-condensed',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robotoCondensed} antialiased`}
      >
        <div className="flex items-start justify-center flex-1 relative max-w-[1080px] mx-auto">
          <QueryProvider>{children}</QueryProvider>
        </div>
      </body>
    </html>
  );
}
